### ISSUE TITLE
dsl method xlsx fails

### ISSUE THREAD

**Issue by unenemy** [randym/activeadmin-axlsx#1]
I tried t o configure xlsx format with code:

  xlsx do
    column :id
  end

But got an error:
uninitialized constant ActiveAdmin::Axlsx::DSL::XlsxBuilder

I tried restarting server and oops I got another error:
undefined method `xlsx' for #ActiveAdmin::ResourceDSL:0xafaef38 (NoMethodError)

Thanks.

**Comment by randym** [comment]
Hi @unenemy

Can you let me know a bit more about how you are doing this?
For example, are you trying to configure this in ActiveAdmin.register [Model] block?
Somewhere in a controller?

More than happy to help out, and fix anything that may be broken, I just need to be able to recreate the problem and dig in.

**Comment by unenemy** [comment]
Okay, I register a Model like this:

ActiveAdmin.register Order, :as => "OrderStatistics" do
end

And xlsx works perfectly, loads an xlsx file with all the field, thats nice.
But when I tried customize it. My customization ended with:

ActiveAdmin.register Order, :as => "OrderStatistics" do
  xlsx do
  end
end

After adding this 2 lines it gives me those errors.
Thanks for quick reply :)
PS: does that matters, my active_admin version is "0.5.0"?

**Comment by randym** [comment]
Please have a look at the readme for this gem. configuration is done via the config builder object. I am not quite sure where you are getting that 'xlsx' from. Perhaps there is some reference out there that I dont know about giving the wrong information?

**Comment by unenemy** [comment]
I found this in your code. That's where I get info about xlsx method

module ActiveAdmin
  module Axlsx
    module DSL
      # Configure the xlsx format
      #
      # For example:
      #
      #   xlsx do
      #     i18n_scope = [:active_admin, :resources, :post]
      #     column :name
      #     column(:author) { |post| post.author.full_name }
      #   end
      #
      #   xlsx :header_style => { :bg_color => "00", :fg_color => "FF" } do
      #     column :name
      #   end
      def xlsx(options={}, &block)
        config.xlsx_builder = XlsxBuilder.new(options, &block)
      end

```
end
```

  end
end

Besides, I have another problem. I tried out the config builder object and it worked fine. I added it this way
ActiveAdmin.register Currency do
   config.xlsx_builder.column('test') do
     "test"
   end

   #xlsx do
   #end
end

BUT. After I tried restart my server, I've got an error:  
undefined method `xlsx_builder' for #ActiveAdmin::Resource:0xbd5b62c (NoMethodError)

I'm sorry for giving you my troubles, but I really need configure output file ( remove some columns, add another columns (using config I can do only adding new)).

Thanks.

**Comment by randym** [comment]
Well done mate! 

Please accept my sincerest apologies for providing the only thing worse than no documentation: bad documentation!

In the short term, can you use the config.axlsx_builder blocks like the README shows?
I am fairly sure you have access to the columns collection and can hack on that without issue.

I'll have a look at that DSL tomorrow and see what is going on (JST here, so time for bed soon!)

**Comment by unenemy** [comment]
Yeap, I can hack that with axlsx_builder, but I'm very waiting for dsl :)
Thanks and good night :)

**Comment by randym** [comment]
Some goodies coming for us soon. Any chance I can encourage you to do some testing against master?

**Comment by unenemy** [comment]
Thanks a lot, that's was fast. For now, that's all I've found.

**Comment by warpc** [comment]
Hi!

I also have this problem: https://github.com/randym/activeadmin-axlsx/issues/4

Do you need any additional informations?

**Comment by randym** [comment]
Does it happen in master?

**Comment by warpc** [comment]
Hi! 

Yes, i insert Gemfile in:

```
 gem 'activeadmin-axlsx', :git => "git@github.com:randym/activeadmin-axlsx.git"
```

Use bundle install and try to run application using rails s

```
 orders.rb:63:in `block in <top (required)>': undefined method `xlsx_builder' for #    <ActiveAdmin::Resource:0x007fad6cc205a8> (NoMethodError)
```

In this file this code is:

```
 xlsx do 
```

I try use 

```
  config.xlsx_builder.delete_columns :id, :created_at, :updated_at
```

and also get error:

```
 7:in `block in <top (required)>': undefined method `xlsx_builder' for #<ActiveAdmin::Resource:0x007fbb7af22780> (NoMethodError)
```

**Comment by randym** [comment]
Thank you very much! I'll try and have a look at this tomorrow morning.

**Comment by warpc** [comment]
Hi. Do you need any additional informations or help with testing changes?

**Comment by warpc** [comment]
@randym, please look it: https://github.com/randym/activeadmin-axlsx/issues/4#issuecomment-14550195
