### ISSUE TITLE
Export all records without pagination

### ISSUE THREAD

**Issue by tommyalvarez** [randym/activeadmin-axlsx#11]
Hi! I couldn't find it anywhere, is there a way to export all records without pagination getting involved? E.g. I'm in the active admin index view of Users and when i export as xlsx only the current page is exported. How can i export ALL records?

**Comment by th1988** [comment]
I solved it with overwriting the collection method like this:

``` ruby
  controller do

    protected

    def collection
      if params[:format].eql?("xlsx")
        @users ||= User.all
      else
        @users ||= User.page(params[:page]).per(50)
      end 

    end 
  end
```

**Comment by randym** [comment]
hi @tommyalvarez 

What @th1988 posted is exactly what you need to do.
activeadmin-axlsx does not, and should not have any control over what the collection contains.
