### ISSUE TITLE
wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by sangyongjung** [randym/activeadmin-axlsx#31]
It seems that the gem is not compatible with active_admin 1.0.0 yet, while it is required if using rails 4.1. :(

**Comment by randym** [comment]
Sorry - I'm working on an update...

**Comment by AhmedNadar** [comment]
Same issue here.
@randym Do you using specific version would solve the issue for now?
Thanks

**Comment by xenda** [comment]
Is there any update with this issue?

**Comment by jcavalieri** [comment]
same

**Comment by mohsen-alizadeh** [comment]
You have to change one line in activeadmin gem

Open file lib/active_admin/resource_controller/streaming.rb in activeadmin

Change line 11
     def index
to 
      def index(arg=nil)

And enjoy yourself :+1:

**Comment by besi** [comment]
+1

**Comment by Jamevidi** [comment]
Works =) Thanks!  

Im using: 
activeadmin 1.0.0.pre, 
rails 4.0.2

**Comment by sangyongjung** [comment]
Thanks all!

**Comment by codemilan** [comment]
sorry for this baby question, but how to edit that file, I'm not getting that file ? I'm too facing the same problem, also if we edit that file, will it work in production environment?

**Comment by bacrossland** [comment]
@coderawal fork the repository, update the file in your fork, install the gem from your updated fork and you should have the fix.

**Comment by codemilan** [comment]
thanks bacrossland, got it working.

**Comment by vkeziah** [comment]
Any solution ? How to solve this issue on heroku ?

**Comment by vkeziah** [comment]
I am facing same issue with rails 4.2.2

**Comment by vkeziah** [comment]
@randym do you have any solution for this
