### ISSUE TITLE
required)>': undefined method `xlsx' for #<ActiveAdmin::ResourceDSL:0x007fca01d1fdd0> (NoMethodError)

### ISSUE THREAD

**Issue by warpc** [randym/activeadmin-axlsx#4]
Hi! 

Thanks for usefull gem and your work.

I have some strange problem with gem. I install it, it work. I customize xlsx for own needs and it work without problem when application run in devel mode. But if stop application and try to start it: i get such error:

```
 app/admin/orders.rb:55:in `block in <top (required)>': undefined method `xlsx' for #      <ActiveAdmin::ResourceDSL:0x007fca01d1fdd0> (NoMethodError)
 gems/activeadmin-0.5.1/lib/active_admin/dsl.rb:16:in `instance_eval'
 gems/activeadmin-0.5.1/lib/active_admin/dsl.rb:16:in `run_registration_block'
 gems/activeadmin-0.5.1/lib/active_admin/namespace.rb:175:in `parse_registration_block'
```

Any idea how fix it?

rails (3.2.12),  activeadmin (0.5.1), activeadmin-axlsx (2.0.0)

**Comment by randym** [comment]
I'll have a look. Thank you for reporting this.

**Comment by Fivell** [comment]
I fixed it by changing after_initialize to before_initialize

**Comment by warpc** [comment]
@Fivell Thanks, it works!

What made in detail: change https://github.com/randym/activeadmin-axlsx/blob/master/lib/active_admin/axlsx.rb#L9 from after_initialize to before_initialize as recomend by @Fivell and all work now.

**Comment by Gerald1985** [comment]
Hi, I was having the same issue, thanks @Fivell it works.
@Radym would you please assist with an update to not override the code.
It crashed at starting the server undefined method `xlsx' for #<ActiveAdmin::ResourceDSL. 

Thanks :)

**Comment by randym** [comment]
Well done @Fivell !
2.0.1 will be on Rubygems shortly.

**Comment by Jamevidi** [comment]
Below version seems to work really well with the "xlsx do...end" - DSL (I just cant get params)  
gem 'activeadmin-axlsx', '2.0.1'

I have tried many other versions of activeadmin-axlsx together with different versions of activeadmin the dsl seems to break for me after this commit https://github.com/randym/activeadmin-axlsx/commit/06b16f820493e46603150e926150188a5a6a6a93
