### ISSUE TITLE
mangle values for specific columns without deleting and re-adding.

### ISSUE THREAD

**Issue by codeho** [randym/activeadmin-axlsx#7]
Hi,

i was wondering if it would be possible to add some sort of 
column_replace(:column_name { |resource| some_helper_function(resource.title) } )

to replace the value of a column.

this would be extremely helpful if one only wants to 'mangle' a few columns. 
This way one wouldn't have to do _all_ columns manually.

**Comment by randym** [comment]
This is being handled here - https://github.com/randym/activeadmin-axlsx/issues/9
